### PR TITLE
Fix deprecated method File.exists? to File.exist?

### PR DESCRIPTION
**Pull request by tuttiq**
Fix for this issue: https://github.com/documentcloud/docsplit/issues/158

Fixes compatibility with ruby 3.2.

### CODE REVIEW

**Comment by tuttiq** [comment]
@knowtheory @jashkenas Any chance we get this merged?

**Comment by tsotne-m** [comment]
@tuttiq any news about this topic?
I just encountered this issue. Maybe you used alternative for gem and could you tell me which one?

**Comment by tuttiq** [comment]
@tsotne-m (cc @tmaier) I ended up pointing the source for the gem (on my project's Gemfile) to my forked version: https://github.com/tuttiq/docsplit

Not great, but I figured this repository is no longer being maintained 🤷‍♀️ I don't plan on maintaining my fork either (since I'm not working on that project anymore), so I recommend you maintain your own forks if you need this gem long term.

**Comment by tsotne-m** [comment]
@tuttiq Thanks a lot for response

**Comment by krystof-k** [comment]
I'm just working on getting rid of Docsplit as well and it depends on your usecase, but in my case of using it to extract word processing documents, it looks like switching to something like [libreconv](https://github.com/DocSpring/libreconv) (or just LibreOffice directly) to convert the document to PDF and then use [pdf-reader](https://github.com/yob/pdf-reader) to extract the text is the way to go.

**Comment by tmaier** [comment]
I consider to use [Apache Tika](https://tika.apache.org) in the future. Especially, a [tika microservice](https://github.com/apache/tika-docker).

It has a simple REST API to extract text. See https://cwiki.apache.org/confluence/display/TIKA/TikaServer#TikaServer-GettheTextofaDocument

**Comment by abratashov** [comment]
Why this PR isn't merged? This is a common issue for all +Ruby 3.2 projects...
CC: @jashkenas @anujaware

**Comment by abratashov** [comment]
:heart:

**Comment by ckim2013** [comment]
have these changes been pushed to rubygems by any chance? as a workaround for our projects, we had to point the our gem to this repo's git directly.

**Pull request merged**
