### PR TITLE
Add layout option to keep layout during text extraction

### PR DESCRIPTION
**Pull request by scarfacedeb**
It allows to preserve layout of pdf in text.

I noticed that `pdftotext` produces better results with `-layout` option with some pdf files. (e.g. table of contents look a lot better and closer to the original markup) 

At first, I implemented passing of random options to `pdftotext` command, but later realised that I only need it for `-layout` option.

### CODE REVIEW

**Comment by scarfacedeb** [comment]
@knowtheory any news on this one?

**Comment by alexandremello** [comment]
I need this feature too.

Is there anybody here?

**Comment by scarfacedeb** [comment]
Unfortunately it seems like this project is dead

**Comment by knowtheory** [comment]
Well that's one way to get my attention (which i probably shouldn't encourage).

Thank you very much for the commit and the extraction here :)

**Comment by scarfacedeb** [comment]
@knowtheory That was a pleasant surprise 😄 Thank you!

**Comment by knowtheory** [comment]
You're welcome!  Happy to talk about other issues over the short term, and things to tackle too :)

**Comment by scarfacedeb** [comment]
Do you have something in mind? 🤔

Btw, could you release new version to rubygems? It'll be great to get rid of the ugly `github:` dependency in gemfile

**Pull request merged**
